compatibility_date = "2026-01-20"
name = "r2-webdav"
main = "./dist/index.js"

compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "webdav"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[build]
command = "pnpm exec tsc"
watch_dir = "src"
